"""R357 — post-generation truncation guard (detect + repair + fallback).

The wrapper-level guards (R102 structural, R142 incomplete-verdict) catch a
cut stream and DISCARD the whole Stage-2 polish. R357 adds a post-generation
guard inside ``_two_stage_generate`` that runs on the FINAL text that would
ship: an incomplete final sentence is REPAIRED with one bounded completion
call (``_attempt_stage2_tail_repair``), falling back to the complete
deterministic Stage-1 answer only when repair fails. It never ships a
structurally-broken fragment.

Stage-2-only by construction (the deterministic davidath bench never reaches
``_two_stage_generate``'s tail), so the deterministic path is byte-identical.
"""

from __future__ import annotations

import pytest

from app.engines.graph_rag import (
    _attempt_stage2_tail_repair,
    _guard_stage2_truncation,
    _looks_incomplete_final_sentence,
    _looks_structurally_truncated,
    _stage2_truncation_guard_enabled,
)
from app.engines.graph_rag.models import GraphContext
from app.integrations.regenold.models import normalise_answer_for_regenold


# ---------------------------------------------------------------------------
# Detector — _looks_incomplete_final_sentence
# ---------------------------------------------------------------------------
class TestLooksIncompleteFinalSentence:
    @pytest.mark.parametrize(
        "text",
        [
            # mid-word cut — the R102 symptom, still the structural guard's job.
            "...intended to be used as a safety component of a produc",
            # R357 — an ending ellipsis is a CUT, not a terminator.
            "The system is high-risk under Article 6(1)…",
            "Article 26 imposes deployer obligations…",
            # R142 promissory verdict (period-terminated but verdict-less).
            "This follows from Article 6(1), which classifies a safety "
            "component as high-risk. Applying that test to the facts.",
            "The operative reasoning.",
            "The prohibited practices are the following:",
            # dangling connector as the final word.
            "The system would be high-risk where it is a medical device and",
            "Article 26 imposes deployer obligations which",
            "The provider must comply with",
            "Both routes lead to high-risk classification under",
            "The deployer retains the logs for a period of",
        ],
    )
    def test_fires_on_truncated_endings(self, text: str) -> None:
        assert _looks_incomplete_final_sentence(text) is True

    @pytest.mark.parametrize(
        "text",
        [
            "The system is high-risk under Article 6(1) read with Annex I.",
            "Article 26 applies. The deployer must assign human oversight.",
            "Yes. The system is high-risk under Article 6(1) and Annex I.",
            "Both routes lead to high-risk classification.",
            "The deployer retains the logs automatically generated by the system.",
            "Article 6(3) exempts the system where it performs a narrow "
            "procedural task.",
            "",
            "   ",
        ],
    )
    def test_does_not_fire_on_complete_answers(self, text: str) -> None:
        assert _looks_incomplete_final_sentence(text) is False

    def test_structural_ellipsis_hole_fixed(self) -> None:
        # Pre-R357, "…" sat in the structural guard's terminal set, so a
        # stream cut right after an ellipsis shipped a broken fragment.
        cut = "The obligations are set out in Article 26(2)…"
        assert _looks_structurally_truncated(cut) is True
        assert _looks_incomplete_final_sentence(cut) is True


# ---------------------------------------------------------------------------
# Guard — _guard_stage2_truncation
# ---------------------------------------------------------------------------
class TestGuardStage2Truncation:
    def _ctx(self) -> GraphContext:
        return GraphContext(question="q")

    def test_complete_polish_ships_unchanged(self) -> None:
        out, used = _guard_stage2_truncation(
            "q", "The system is high-risk under Article 6(1).", "kg", self._ctx()
        )
        assert out == "The system is high-risk under Article 6(1)."
        assert used is True

    def test_truncated_repair_success_ships_repaired(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def fake_repair(question, enhanced, kg_answer, context):  # noqa: ARG001
            return "The system is high-risk under Article 6(1) read with Annex I."

        monkeypatch.setattr(
            "app.engines.graph_rag._attempt_stage2_tail_repair", fake_repair
        )
        out, used = _guard_stage2_truncation(
            "q",
            "The system would be high-risk where it is a medical device and",
            "kg",
            self._ctx(),
        )
        assert out == "The system is high-risk under Article 6(1) read with Annex I."
        assert used is True

    def test_truncated_repair_failure_falls_back_to_kg(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        def fake_repair(question, enhanced, kg_answer, context):  # noqa: ARG001
            return None

        monkeypatch.setattr(
            "app.engines.graph_rag._attempt_stage2_tail_repair", fake_repair
        )
        out, used = _guard_stage2_truncation(
            "q",
            "The system would be high-risk where it is a medical device and",
            "DETERMINISTIC_KG",
            self._ctx(),
        )
        assert out == "DETERMINISTIC_KG"
        assert used is False

    def test_tiny_fragment_falls_back_without_repair(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # A fragment shorter than the repair floor short-circuits inside the
        # real repair helper (no provider call) → deterministic fallback.
        called = []

        def fake_complete(**kw):  # noqa: ARG001
            called.append(True)
            return "x"

        monkeypatch.setattr(
            "app.engines.graph_rag._stage2_complete", fake_complete
        )
        out, used = _guard_stage2_truncation(
            "q", "safety component of a produc", "DETERMINISTIC_KG", self._ctx()
        )
        assert out == "DETERMINISTIC_KG"
        assert used is False
        assert not called  # nothing worth repairing → no provider call


# ---------------------------------------------------------------------------
# Repair — _attempt_stage2_tail_repair (real splice, stubbed provider call)
# ---------------------------------------------------------------------------
class TestAttemptStage2TailRepair:
    def _ctx(self) -> GraphContext:
        return GraphContext(question="q")

    def test_clause_cut_splices_at_word_boundary(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The cut lands BETWEEN words, so the model leads the tail with a space.
        monkeypatch.setattr(
            "app.engines.graph_rag._stage2_complete",
            lambda **kw: " under Article 6(1) if it is a medical device.",
        )
        out = _attempt_stage2_tail_repair(
            "q",
            "The system would be high-risk where it is a safety component of a "
            "regulated product",
            "kg",
            self._ctx(),
        )
        assert out is not None
        assert out.endswith(
            "regulated product under Article 6(1) if it is a medical device."
        )
        assert _looks_incomplete_final_sentence(out) is False

    def test_mid_word_cut_splices_without_space(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The cut lands MID-WORD, so the model continues the word (no space).
        monkeypatch.setattr(
            "app.engines.graph_rag._stage2_complete",
            lambda **kw: "t is a safety component of a regulated product.",
        )
        out = _attempt_stage2_tail_repair(
            "q",
            "The system is classified as high-risk under Article 6(1) where it "
            "is intended to be used as a safety component of a produc",
            "kg",
            self._ctx(),
        )
        assert out is not None
        assert out == (
            "The system is classified as high-risk under Article 6(1) where it "
            "is intended to be used as a safety component of a product is a "
            "safety component of a regulated product."
        )
        assert _looks_incomplete_final_sentence(out) is False

    def test_repeat_model_output_rejected(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # A model that re-answers the whole thing must be rejected.
        monkeypatch.setattr(
            "app.engines.graph_rag._stage2_complete",
            lambda **kw: " The system would be high-risk where it is a safety "
            "component of a regulated product.",
        )
        out = _attempt_stage2_tail_repair(
            "q",
            "The system would be high-risk where it is a safety component of a "
            "regulated product",
            "kg",
            self._ctx(),
        )
        assert out is None

    def test_still_incomplete_repair_rejected(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # A repair that itself ends truncated must not ship.
        monkeypatch.setattr(
            "app.engines.graph_rag._stage2_complete",
            lambda **kw: " under Article 6(1) if it is a medical device and",
        )
        out = _attempt_stage2_tail_repair(
            "q",
            "The system would be high-risk where it is a safety component of a "
            "regulated product",
            "kg",
            self._ctx(),
        )
        assert out is None

    def test_empty_tail_rejected(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(
            "app.engines.graph_rag._stage2_complete", lambda **kw: "   "
        )
        out = _attempt_stage2_tail_repair(
            "q",
            "The system would be high-risk where it is a safety component of a "
            "regulated product",
            "kg",
            self._ctx(),
        )
        assert out is None


# ---------------------------------------------------------------------------
# Flag gating + byte-identity on the deterministic path
# ---------------------------------------------------------------------------
class TestGuardFlag:
    def test_default_on(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.delenv("REGENOLD_STAGE2_TRUNCATION_GUARD", raising=False)
        assert _stage2_truncation_guard_enabled() is True

    def test_env_off_disables(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("REGENOLD_STAGE2_TRUNCATION_GUARD", "0")
        assert _stage2_truncation_guard_enabled() is False

    def test_guard_off_is_byte_identical(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # With the guard disabled, the guard is a no-op on complete text — this
        # pins the Stage-1-only (davidath) path byte-identity.
        monkeypatch.setenv("REGENOLD_STAGE2_TRUNCATION_GUARD", "0")
        text = "The system is high-risk under Article 6(1) read with Annex I."
        out, used = _guard_stage2_truncation(
            "q", text, "kg", GraphContext(question="q")
        )
        assert out == text
        assert used is True


# ---------------------------------------------------------------------------
# Measurement — the judge-flagged truncation-failure rows (R350.2 taxonomy)
# ---------------------------------------------------------------------------
class TestTruncationFailureRows:
    """The deterministic Stage-1 answers for the judge's 'truncated' rows must
    never ship a structurally-broken fragment, and the detector must flag the
    exact cut shapes the judge quoted ('internal-control.', mid-sentence cuts)."""

    ROWS = {
        # la_q13 — GPAI transparency exceptions (R356 curated intercept).
        "la_q13": "Under what conditions should providers of general-purpose "
        "AI models be subject to exceptions regarding transparency-related "
        "requirements, if any? And what do those exceptions not cover?",
        # la_q23 — systemic-risk scope (R356 curated intercept).
        "la_q23": 'Does "systemic risk" apply to AI systems or general '
        "purpose AI models or both?",
        # la_q53 — customer-support chatbot.
        "la_q53": "We are building a chatbot for customer support. What do "
        "we need to know?",
        # la_q72 — provider pre-market duties for a medical diagnostic system.
        "la_q72": "What must the provider of a high-risk AI medical "
        "diagnostic system put in place before placing it on the market?",
        # la_q78 — pharma foundation model > 10^25 FLOPs.
        "la_q78": "A pharma company trains a large foundation model for drug "
        "discovery whose training compute exceeds 10^25 FLOPs. Which EU AI "
        "Act obligations apply?",
        # la_q86 — health-insurance risk assessment and pricing.
        "la_q86": "What does the EU AI Act require for an AI system used for "
        "risk assessment and pricing in health insurance?",
    }

    @pytest.mark.parametrize("qid", sorted(ROWS))
    def test_stage1_answer_never_structurally_truncated(self, qid: str) -> None:
        from app.engines._graph_rag_impl import _deterministic_answer

        q = self.ROWS[qid]
        ctx = GraphContext(question=q)
        ans = _deterministic_answer(q, ctx)
        assert ans.strip()
        assert _looks_incomplete_final_sentence(ans) is False, (
            f"{qid} Stage-1 answer ends truncated: {ans[-80:]!r}"
        )
        # The normaliser (route-level) must also never leave a fragment.
        norm = normalise_answer_for_regenold(ans, question=q)
        assert _looks_incomplete_final_sentence(norm) is False, (
            f"{qid} normalised answer ends truncated: {norm[-80:]!r}"
        )

    @pytest.mark.parametrize(
        "fragment",
        [
            # The judge-quoted Q72 shape: a bare fragment ending mid-word.
            "internal-control. Article 10 requires",
            # Q13: a single fragment with nothing after the lead-in.
            "Only a single fragment regarding systemic risk:",
            # Q53: a last sentence cut before its object.
            "A standard customer support chatbot sits outside the high-risk "
            "regime, and the operator's obligations turn on whether",
        ],
    )
    def test_judge_quoted_cut_shapes_are_detected(self, fragment: str) -> None:
        assert _looks_incomplete_final_sentence(fragment) is True
