"""Verbatim EU AI Act provision text — sub-point-resolved access layer.

The single entry point for "give me the exact regulatory text for this
citation" — used by the R94 verbatim answer mode so the wire quotes the
Official Journal word-for-word (no paraphrase) down to the sub-point
(``Article 111(2)``, ``Article 6(1)``, ``Article 5(1)(a)``, ``Annex
IV(2)``, ``Article 3(1)`` definition).

Source of truth: :data:`app.data.official_eu_ai_act.OFFICIAL_ARTICLE_TEXT`
(EUR-Lex CELEX 32024R1689, SHA-pinned) with
:data:`app.data.official_text_patches.OFFICIAL_TEXT_PATCHES` merged on top
(curated verbatim repairs that survive a re-fetch of the autogenerated
module).

Resolution rules:

* ``Article N``            → the full article body (title stripped).
* ``Article N(M)``         → paragraph M of article N (numbered ``M.`` block).
* ``Article N(M)(x)``      → lettered point ``(x)`` inside paragraph M.
* ``Article 3(K)``         → definition ``(K)`` (Art. 3 uses parenthesised
                             ``(1)…(68)`` numbering, not ``1.`` paragraphs).
* ``Annex X``              → the full annex body (title stripped).
* ``Annex X(M)``           → numbered item M of annex X.

Every form accepts the internal (``Art. 5(1)(a)``), user-facing
(``Article 5.1.a``) or bare (``Article 5``) shapes — parsing is delegated
to :mod:`app.integrations.regenold.refs`.

Returns ``None`` when the ref doesn't resolve (unknown article, or a
sub-point the stored text doesn't expose) so callers can fall back to a
coarser granularity. Pure stdlib; no network.
"""
from __future__ import annotations

import re
from functools import lru_cache

from app.data.article_existence import ARTICLE_EXISTENCE
from app.data.official_eu_ai_act import (
    OFFICIAL_ANNEX_TITLES,
    OFFICIAL_ARTICLE_TEXT,
    OFFICIAL_ARTICLE_TITLES,
)
from app.data.official_text_patches import OFFICIAL_TEXT_PATCHES
from app.integrations.regenold import refs as _refs

__all__ = [
    "get_provision_text",
    "provision_exists",
    "article_body",
    "select_relevant_paragraphs",
]

# Lightweight stopword set for paragraph relevance scoring (R94.1). Kept
# tiny on purpose — just the high-frequency function words that would
# otherwise dominate token-overlap.
_STOP = frozenset(
    "the a an of to in on for and or as is are be by with that this which "
    "what when who how do does shall must may any all its their our we us "
    "eu ai act article articles annex regulation system systems".split()
)

# Patches win over the autogenerated text.
_TEXT: dict[str, str] = {**OFFICIAL_ARTICLE_TEXT, **OFFICIAL_TEXT_PATCHES}
_TITLES: dict[str, str] = {**OFFICIAL_ARTICLE_TITLES, **OFFICIAL_ANNEX_TITLES}

# ── splitters ────────────────────────────────────────────────────────────
#
# Tuned for OFFICIAL_ARTICLE_TEXT's single-string, title-prefixed shape.
# A paragraph heading is ``N.`` at start-of-text or after clause-end
# punctuation + whitespace (the R34 discipline — avoids matching
# back-references like "in paragraph 2." inside a body).

_PARA_RE = re.compile(r"(?:^|(?<=[\n;.!?])\s+)(\d{1,2})\.\s+")
# Lettered list item: ``: (a) `` / ``; (b) `` — leading punctuation marks
# a real list item, not a back-reference like "point (h) of ...".
_SUBPOINT_RE = re.compile(r"[:;]\s+(?:or\s+|and\s+)?\(([a-z]{1,4})\)\s")
# Annex numbered item: ``: 1. Foo`` / ``. 2. Bar`` followed by a capital.
_ANNEX_ITEM_RE = re.compile(r"(?:^|[.:;]\s)(\d{1,2})\.\s+(?=[A-Z])")
# Art. 3 definition: ``apply: (1) '…' means`` / ``; (2) …`` — parenthesised
# number at start or after clause punctuation. The colon is included so the
# opening ``the following definitions apply: (1)`` is captured.
_DEF_RE = re.compile(r"(?:^|(?<=[\n;.:!?])\s+)\((\d{1,3})\)\s+")


def _short_to_long(short: str) -> str | None:
    """``Art. 111`` → ``Article 111``; ``Annex IV`` stays ``Annex IV``."""
    s = short.strip()
    if s.startswith("Art. "):
        return "Article " + s[len("Art. "):].strip()
    if s.startswith("Article ") or s.startswith("Annex "):
        return s
    return None


def _strip_title(long_key: str, text: str) -> str:
    title = (_TITLES.get(long_key, "") or "").strip()
    body = text.strip()
    if title and body.startswith(title):
        body = body[len(title):].strip()
    return body


@lru_cache(maxsize=256)
def article_body(long_key: str) -> str | None:
    """Verbatim article/annex body (title stripped), patches applied.

    ``long_key`` is ``"Article N"`` or ``"Annex X"``. Returns ``None`` when
    the key isn't in the corpus.
    """
    text = _TEXT.get(long_key)
    if not text:
        return None
    return _strip_title(long_key, text)


def _paragraphs(body: str) -> dict[int, str]:
    """Map ``{paragraph_number: text}`` for numbered ``N.`` paragraphs.

    Anchors at the first ``1.`` heading and accepts strictly ascending
    ``2., 3., …`` so a stray digit inside a body can't fork the sequence.
    Empty dict when the article carries no numbered paragraphs.
    """
    ms = list(_PARA_RE.finditer(body))
    if not ms:
        return {}
    start_i = next((i for i, m in enumerate(ms) if int(m.group(1)) == 1), None)
    if start_i is None:
        return {}
    seq = []
    expected = 1
    for m in ms[start_i:]:
        if int(m.group(1)) == expected:
            seq.append(m)
            expected += 1
    out: dict[int, str] = {}
    for j, m in enumerate(seq):
        n = int(m.group(1))
        end = seq[j + 1].start() if j + 1 < len(seq) else len(body)
        out[n] = body[m.end():end].strip()
    return out


def _subpoints(paragraph_text: str) -> dict[str, str]:
    """Map ``{letter: text}`` for ``(a)(b)(c)…`` list items in a paragraph."""
    ms = list(_SUBPOINT_RE.finditer(paragraph_text))
    out: dict[str, str] = {}
    for j, m in enumerate(ms):
        letter = m.group(1)
        end = ms[j + 1].start() if j + 1 < len(ms) else len(paragraph_text)
        out[letter] = paragraph_text[m.end():end].strip().rstrip(" ;.")
    return out


def _annex_items(body: str) -> dict[int, str]:
    ms = list(_ANNEX_ITEM_RE.finditer(body))
    out: dict[int, str] = {}
    for j, m in enumerate(ms):
        n = int(m.group(1))
        end = ms[j + 1].start() if j + 1 < len(ms) else len(body)
        out[n] = body[m.end():end].strip()
    return out


# ── Nesting-aware sub-point parser (graph ingest only) ─────────────────────
#
# ``_subpoints`` above FLATTENS a paragraph's list into a single ``{letter:
# text}`` dict — which mislabels the nested roman carve-outs ``(i)(ii)(iii)``
# (e.g. Art. 5(1)(c) social-scoring, Art. 5(1)(h) real-time RBI, Art. 13(3)(b)
# instructions-for-use) as top-level "letters" AND COLLIDES the romans of two
# different letters (5(1)(c)(i) and 5(1)(h)(i) both become key ``"i"``,
# last-write-wins → data loss). That is fine for the wire (it only ever quotes
# a single leaf), but WRONG for the graph, which must carry the faithful tree.
#
# ``subpoints_nested`` is the additive, nesting-aware parser used ONLY by the
# Neo4j seed hierarchy. It is intentionally NOT wired into the wire path, so
# the davidath bench + every ``_subpoints`` consumer stay byte-identical.
#
# Disambiguation rule (verified against the corpus): a roman-valued marker
# introduced by ``:`` opens a nested list under the current letter; a marker
# that continues the top-level ``a→b→c…`` letter sequence is a letter (so
# Art. 16's real letter ``(i)`` — delimiter ``;``, continues h→i→j → stays a
# letter, while Art. 5(1)(h)'s roman ``(i)`` — delimiter ``:`` after (h)'s
# "…for one of the following objectives:" chapeau → nests under (h)).

# Same shape as ``_SUBPOINT_RE`` but captures the leading ``: / ;`` delimiter
# so the letter-vs-roman disambiguation can read it.
_NESTED_SUBPOINT_RE = re.compile(r"([:;])\s+(?:or\s+|and\s+)?\(([a-z]{1,4})\)\s")

# Roman-numeral markers that can be a NESTED sub-point under a letter. Limited
# to the range the Act actually uses (Art. 5(1)(h) reaches (iii); no provision
# nests past ~(vii)); ``x`` deliberately excluded so a genuine letter ``(x)``
# is never mis-nested.
_NESTED_ROMANS: tuple[str, ...] = (
    "i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix",
)


def subpoints_nested(paragraph_text: str) -> dict[str, dict]:
    """Parse a paragraph into ``{letter: {"text": str, "subs": {roman: str}}}``.

    Verbatim throughout — only WHERE the split boundaries fall is decided; no
    text is rewritten. Preserves insertion order (letters a→h, then each
    letter's nested romans i→iii). Returns an empty dict for a paragraph with
    no lettered list items.

    See the module comment above for the letter-vs-roman disambiguation rule.
    """
    text = paragraph_text or ""
    ms = list(_NESTED_SUBPOINT_RE.finditer(text))
    if not ms:
        return {}

    out: dict[str, dict] = {}
    cur_letter: str | None = None
    expected_letter = "a"
    in_nested = False
    expected_roman_idx = 0  # index into _NESTED_ROMANS for the open nested list

    for j, m in enumerate(ms):
        key = m.group(2)
        delim = m.group(1)
        end = ms[j + 1].start() if j + 1 < len(ms) else len(text)
        body = text[m.end():end].strip().rstrip(" ;.")

        is_roman = key in _NESTED_ROMANS

        # (a) continue an already-open nested roman sequence: i→ii→iii …
        if (
            in_nested
            and cur_letter is not None
            and is_roman
            and expected_roman_idx < len(_NESTED_ROMANS)
            and key == _NESTED_ROMANS[expected_roman_idx]
        ):
            out[cur_letter]["subs"][key] = body
            expected_roman_idx += 1
            continue

        # (b) OPEN a nested roman list under the current letter: ``: (i) …``
        if is_roman and delim == ":" and cur_letter is not None and key == "i":
            in_nested = True
            out[cur_letter]["subs"]["i"] = body
            expected_roman_idx = 1  # next expected is "ii"
            continue

        # (c) a top-level letter that continues the a→b→c… sequence
        if key == expected_letter:
            cur_letter = key
            out[key] = {"text": body, "subs": {}}
            expected_letter = chr(ord(expected_letter) + 1)
            in_nested = False
            expected_roman_idx = 0
            continue

        # (d) fallback — treat as a fresh top-level letter (robustness for an
        # out-of-sequence marker; keeps text rather than dropping it).
        cur_letter = key
        out[key] = {"text": body, "subs": {}}
        expected_letter = chr(ord(key[:1]) + 1) if len(key) == 1 else expected_letter
        in_nested = False
        expected_roman_idx = 0

    return out


def _definitions(body: str) -> dict[int, str]:
    """Art. 3 definitions: ``{number: text}`` from ``(1)…(68)``."""
    ms = list(_DEF_RE.finditer(body))
    out: dict[int, str] = {}
    for j, m in enumerate(ms):
        n = int(m.group(1))
        end = ms[j + 1].start() if j + 1 < len(ms) else len(body)
        out[n] = body[m.end():end].strip()
    return out


def provision_exists(ref: str) -> bool:
    """True iff the base article/annex of ``ref`` is in the existence catalog."""
    try:
        spec = _refs.parse(ref)
    except _refs.InvalidRefError:
        return False
    if spec.is_annex:
        return f"Annex {spec.annex_roman}" in ARTICLE_EXISTENCE
    return f"Art. {spec.article_number}" in ARTICLE_EXISTENCE


def get_provision_text(ref: str) -> str | None:
    """Return the verbatim text for ``ref`` at its finest resolvable granularity.

    Falls back coarser only by returning ``None`` — the caller decides
    whether to retry at article level. ``ref`` may be any of the three
    citation shapes (internal / user-facing / bare).
    """
    try:
        spec = _refs.parse(ref)
    except _refs.InvalidRefError:
        return None

    if spec.is_annex:
        long_key = f"Annex {spec.annex_roman}"
        body = article_body(long_key)
        if body is None:
            return None
        if not spec.subpoints:
            return body
        # Annex item: first sub-point token is the numbered item.
        first = spec.subpoints[0]
        if first.isdigit():
            item = _annex_items(body).get(int(first))
            return item  # None → caller falls back to full annex
        return None

    # Article path.
    n = spec.article_number
    long_key = f"Article {n}"
    body = article_body(long_key)
    if body is None:
        return None
    if not spec.subpoints:
        return body

    first = spec.subpoints[0]
    if not first.isdigit():
        return None

    # Article 3 — parenthesised definition numbering, not ``N.`` paragraphs.
    if n == 3:
        return _definitions(body).get(int(first))

    para = _paragraphs(body).get(int(first))
    if para is None:
        return None
    if len(spec.subpoints) == 1:
        return para
    # Second token = lettered sub-point inside the paragraph.
    second = spec.subpoints[1].lower()
    return _subpoints(para).get(second)


def _stem(w: str) -> str:
    """Light suffix strip so question vocab matches statute vocab —
    ``emotions``→``emotion``, ``scoring``→``scor``, ``recruitment``→
    ``recruit``. Crude but symmetric (applied to both sides)."""
    for suf in ("ing", "ment", "ies", "ed", "s"):
        if len(w) > len(suf) + 2 and w.endswith(suf):
            return w[: -len(suf)] + ("y" if suf == "ies" else "")
    return w


def _tokens(text: str) -> set[str]:
    return {
        _stem(w) for w in re.findall(r"[a-z0-9]+", (text or "").lower())
        if len(w) > 2 and w not in _STOP
    }


def select_relevant_paragraphs(
    ref: str, question: str = "", max_chars: int = 500
) -> str | None:
    """Return the verbatim, question-RELEVANT paragraph(s) of an article/annex.

    R94.1 — the verbatim answer mode (R94) quoted the FULL article for an
    article-level reference, which produced 4k-11k-char wire answers for
    long articles (Art. 5 prohibited-practices, Art. 6, Annex III) and
    tanked the conciseness axis (live judge: 0.09). This selects the
    paragraph(s) whose tokens best overlap the question and returns them
    verbatim (paragraph ``N.`` markers preserved, complete paragraphs —
    NEVER mid-sentence truncation, honouring "exact text, no
    reformulation"), bounded to ``max_chars``.

    Selection: score each numbered paragraph (article) / item (annex) by
    question-token overlap; emit in document order, highest-scoring first
    up to the budget. The top-scoring paragraph is ALWAYS included even if
    it alone exceeds ``max_chars`` (a complete paragraph beats a truncated
    one). When the article has no numbered paragraphs (single block) or no
    question signal, falls back to the leading paragraph / the whole body
    if it already fits. Returns ``None`` when the base ref doesn't resolve
    (caller keeps the full-body path).
    """
    try:
        spec = _refs.parse(ref)
    except _refs.InvalidRefError:
        return None
    if spec.subpoints:
        # Sub-point refs are already bounded — quote exactly.
        return get_provision_text(ref)

    if spec.is_annex:
        long_key = f"Annex {spec.annex_roman}"
        body = article_body(long_key)
        if body is None:
            return None
        units = _annex_items(body)
    else:
        n = spec.article_number
        long_key = f"Article {n}"
        body = article_body(long_key)
        if body is None:
            return None
        if n == 3:
            units = {}  # definitions: queried by term, keep full-body fallback
        else:
            units = _paragraphs(body)

    q_tok = _tokens(question)
    if body is not None and len(body) <= max_chars:
        return body  # already concise — quote the whole thing
    if not units:
        # Single-block article (no "N." paragraphs) but possibly a long
        # lettered list (Art. 16 "(a)…(n)"). Drill its sub-points; else
        # the caller-side budget applies to the full body.
        drilled = _drill_subpoints(None, body or "", q_tok, max_chars)
        return drilled if drilled is not None else body

    # (number, text, score) in document order.
    scored = [
        (num, txt, len(q_tok & _tokens(txt)))
        for num, txt in sorted(units.items())
    ]
    # Rank by score (desc), then document order (asc) for ties.
    ranked = sorted(scored, key=lambda x: (-x[2], x[0]))
    if q_tok and ranked[0][2] == 0:
        # No question overlap with any paragraph → leading paragraph.
        ranked = sorted(scored, key=lambda x: x[0])

    # If the single best paragraph is itself oversized AND carries lettered
    # sub-points (e.g. Art. 5(1) "(a)…(h)", Annex III "(a)…"), drill one
    # level: quote the paragraph preamble + the question-relevant
    # sub-point(s) verbatim rather than the whole enumeration.
    top_num, top_txt, _top_score = ranked[0]
    if len(top_txt) > max_chars:
        drilled = _drill_subpoints(top_num, top_txt, q_tok, max_chars)
        if drilled is not None:
            return drilled

    chosen: dict[int, str] = {}
    total = 0
    for num, txt, _score in ranked:
        rendered_len = len(txt) + 4  # "N. " + gap
        if chosen and total + rendered_len > max_chars:
            continue
        chosen[num] = txt
        total += rendered_len
        if total >= max_chars:
            break
    # Emit in document order with paragraph numbers preserved (verbatim shape).
    return " ".join(f"{num}. {chosen[num]}" for num in sorted(chosen))


def _drill_subpoints(
    num: int | None, paragraph_text: str, q_tok: set[str], max_chars: int
) -> str | None:
    """Quote a paragraph's preamble + lettered sub-point(s), verbatim.

    Used when a numbered paragraph (or single-block article body) is itself
    a long ``(a)…(h)`` enumeration (Art. 5(1), Art. 6, Art. 16, Annex III).
    Returns ``None`` when there are no lettered sub-points (caller keeps the
    full text). All text is verbatim; only WHICH sub-points are quoted is
    narrowed.

    **Confidence gate** — to never quote the WRONG sub-point on a vocab
    mismatch, the question-relevant sub-point is quoted FIRST only when it
    is a *clear* token-overlap winner (top ≥ 1 AND margin ≥ 1 over the
    second). On a tie / no signal we fall back to document order (chapeau +
    leading sub-points), which is incomplete-but-correct (and the
    references field still cites the full provision). ``num`` is the
    paragraph number prefix (``None`` for a single-block article body).
    """
    subs = _subpoints(paragraph_text)
    if not subs:
        return None
    first = _SUBPOINT_RE.search(paragraph_text)
    preamble = paragraph_text[: first.start() + 1].strip() if first else ""

    scored = sorted(
        ((letter, txt, len(q_tok & _tokens(txt))) for letter, txt in subs.items()),
        key=lambda x: (-x[2], x[0]),
    )
    top = scored[0][2]
    second = scored[1][2] if len(scored) > 1 else 0
    confident = bool(q_tok) and top >= 1 and (top - second) >= 1
    order = (
        [(letter, t) for letter, t, _ in scored] if confident
        else sorted(subs.items(), key=lambda kv: kv[0])  # doc order
    )

    lead = f"{num}. {preamble}".strip() if num is not None else preamble
    out = lead
    added = 0
    for letter, txt in order:
        frag = f" ({letter}) {txt}"
        # Always include the first (winning, or leading) sub-point even if it
        # alone exceeds the budget. Append more only while under budget;
        # never mid-truncate a sub-point.
        if added >= 1 and len(out) + len(frag) > max_chars:
            break
        out += frag
        added += 1
    return out.strip()
