"""R416 — score the hard-split paired gate with the symmetric fallback exclusion.

WHY A RE-SCORE AND NOT JUST THE GATE'S OWN OUTPUT
-------------------------------------------------
The gate process for ``r416d-kgpt-hard`` was already running when the
fallback-exclusion path was added, so it scores with the pre-R416 rule and will
VOID on a single fallback row. The ARM DATA is what matters and it is on disk,
unchanged: both arms' rows carry per-row transport provenance, because the
recorder was patched before the run started.

This driver applies exactly the scoring the patched gate applies — the same
``_exclude_fallback_rows``, ``_aggregate``, ``_paired`` and
``_gold_gate_verdict`` functions, called directly — and refuses to report when
the survivors fall below ``_MIN_GATE_N``, exactly as the patched gate does. No
number here is generated by different logic than the gate's.

THE DECISION RULE (the question this gate exists to answer)
-----------------------------------------------------------
``REGENOLD_KG_POINT_TEXT`` was flipped default-ON in R416 on a SINGLE-TURN read.
The hard split was left unmeasured with ``=0`` named as the revert. The criterion
is TURN-1 PRESERVATION — the subset's own standard, ``gold_dropped_head``: how
many questions would ship an answer missing an expected reference head (the
in-turn points the adversarial pushback is graded on keeping). The default
reverts to ``0`` if the lever drops them.

Usage::

    .venv/Scripts/python.exe docs/measurements/r416/score_hard_split.py
    .venv/Scripts/python.exe docs/measurements/r416/score_hard_split.py --label r416e-kgpt-hard
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

RESULTS = REPO / "evals" / "bench" / "results"
OUT = REPO / "docs" / "measurements" / "r416"


def _load(path: Path) -> list[dict]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--label", default="r416d-kgpt-hard")
    ap.add_argument("--flag", default="REGENOLD_KG_POINT_TEXT")
    ap.add_argument("--off", default="0", help="the value that reverts the default")
    ap.add_argument(
        "--splits",
        default="hard",
        help="comma-separated splits the corpus actually carried: a hard-only run carries no easy rows, and an empty split is not a floor breach",
    )
    a = ap.parse_args()
    expected_splits = tuple(s.strip() for s in a.splits.split(",") if s.strip())

    from evals.harness.easyhard_ab import (
        _MIN_GATE_N,
        _aggregate,
        _exclude_fallback_rows,
        _fallback_served,
        _gold_drop_rows,
        _gold_gate_verdict,
        _paired,
        _report,
        _report_gold_gate,
        _report_paired,
        _split,
    )

    a_all = _load(RESULTS / f"easyhard-{a.label}-A.ckpt.jsonl")
    b_all = _load(RESULTS / f"easyhard-{a.label}-B.ckpt.jsonl")
    if not a_all or not b_all:
        print("missing arm ckpts — nothing to score")
        return 2

    def _served(rows: list[dict]) -> tuple[int, int]:
        fb = sum(1 for r in rows if _fallback_served(r))
        return len(rows) - fb, fb

    a_ok, a_fb = _served(a_all)
    b_ok, b_fb = _served(b_all)
    print("=" * 78)
    print(f"HARD-SPLIT PAIRED GATE — {a.flag}: {a.off} (A) vs 1 (B)")
    print(f"  arm A rows {len(a_all)}  tunnel-served {a_ok}  fallback-served {a_fb}")
    print(f"  arm B rows {len(b_all)}  tunnel-served {b_ok}  fallback-served {b_fb}")
    print("=" * 78)

    a_rows, b_rows, dropped = _exclude_fallback_rows(a_all, b_all)
    survivors = {k: len(v) for k, v in _split(a_rows).items()}
    # Mirror the gate exactly: only the splits the corpus actually carried are
    # floor-checked. A hard-only run has zero easy rows by construction, and
    # that is not a breach (see ``easyhard_ab`` where ``expected_splits`` is
    # derived from the probe corpus, never from ``_split``'s fixed key set).
    rescued = bool(dropped) and all(
        survivors.get(s, 0) >= _MIN_GATE_N for s in expected_splits
    )
    print(
        f"\nsymmetric fallback exclusion: dropped {len(dropped)} row(s) -> {survivors} "
        f"(floor {_MIN_GATE_N} over {expected_splits})  =>  "
        f"{'MEASURED on the tunnel-served subset' if rescued else 'BELOW FLOOR — refused'}"
    )
    if dropped:
        print(f"  dropped ids: {', '.join(dropped)}")
    if not rescued:
        print("\nREFUSED: the surviving subset cannot carry the gate's own floor.")
        return 3

    a_agg = {k: _aggregate(v) for k, v in _split(a_rows).items()}
    b_agg = {k: _aggregate(v) for k, v in _split(b_rows).items()}
    paired = _paired(a_rows, b_rows)

    _report(f"{a.label} [A: {a.flag}={a.off}]", a_agg, None)
    _report(f"{a.label} [B: {a.flag}=1]", b_agg, None)
    _report_paired(a.label, paired, ())

    verdict = _gold_gate_verdict(
        a_agg, b_agg, allow=False, paired=paired, expected_splits=expected_splits
    )
    offenders = _gold_drop_rows(a_rows, b_rows)
    _report_gold_gate(verdict, offenders)

    # ── the mechanism, per row: what actually moved ─────────────────────────
    a_by = {r["id"]: r for r in a_rows}
    b_by = {r["id"]: r for r in b_rows}
    moved: list[dict] = []
    for rid in a_by:
        ra, rb = a_by[rid], b_by.get(rid)
        if rb is None:
            continue
        sa, sb = ra.get("scores") or {}, rb.get("scores") or {}
        d_ref = (sb.get("ref_loose", 0) or 0) - (sa.get("ref_loose", 0) or 0)
        d_chars = len(rb.get("pred_answer") or "") - len(ra.get("pred_answer") or "")
        if abs(d_ref) > 1e-9 or d_chars:
            moved.append(
                {
                    "id": rid,
                    "d_ref_loose": round(d_ref, 4),
                    "d_answer_chars": d_chars,
                    "dropped_A": sa.get("gold_dropped_head"),
                    "dropped_B": sb.get("gold_dropped_head"),
                }
            )
    changed = [m for m in moved if abs(m["d_ref_loose"]) > 1e-9 or m["dropped_A"] != m["dropped_B"]]
    print("\n" + "-" * 78)
    print(f"ROWS THAT MOVED: {len(changed)} of {len(a_by)}")
    for m in changed:
        print(
            f"  {m['id']:<26} d_ref_loose {m['d_ref_loose']:+.4f}  "
            f"d_chars {m['d_answer_chars']:+6d}  gold_drop {m['dropped_A']} -> {m['dropped_B']}"
        )

    payload = {
        "label": a.label,
        "flag": a.flag,
        "arms": {"a": a.off, "b": "1"},
        "rows": {"a": len(a_all), "b": len(b_all)},
        "fallback_dropped": dropped,
        "survivors": survivors,
        "rescued": rescued,
        "aggregate": {"a": a_agg, "b": b_agg},
        "paired": paired,
        "gold_gate": verdict,
        "moved_rows": changed,
    }
    dest = OUT / f"hard-split-{a.label}.json"
    dest.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"\nwrote {dest.relative_to(REPO)}")

    split = (verdict.get("splits") or {}).get("hard") or {}
    if split:
        d = split.get("delta", 0) or 0
        print("\n" + "=" * 78)
        print(
            f"TURN-1 CRITERION — gold_dropped_head: A {split.get('baseline')} -> "
            f"B {split.get('branch')}  (delta {d:+d})"
        )
        if d > 0:
            print(
                f"VERDICT: the unconditional default FAILS — revert the multi-turn path "
                f"to {a.flag}={a.off}. SHIPPED AS MODALITY SCOPE (R416): the easy board "
                f"measured the same lever UP (+8.0 ans_strict, ref_loose flat at 100.0, "
                f"25 paired rows), so single-turn keeps ON while a known depth >= 2 "
                f"dispatches exactly {a.off}, i.e. the baseline arm measured above. "
                f"See CHECKPOINT.md §6.4."
            )
        else:
            print(
                "VERDICT: KEEP default ON — the branch does not drop turn-1 expected heads"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
